version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi

  fastapi:    
    # build the fastapi service using Dockerfile in ./app
    # build: ./app
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi
    # restart: always
    ports:
      - "5000:5000"
