version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi

  fastapi:    
    # build the fastapi service using Dockerfile in ./app
    # build: ./app
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_container
    command: gunicorn --bind 0.0.0.0:5000 server-fastapi:app --worker-class uvicorn.workers.UvicornWorker
    ports:
      - "5000:5000"
