collections = ["behavior", "notification", "activity_recognition", "recent_use", "ESM", "diary", "category"]

data = {
	"behavior_1": {
		"notification_id": 12345,
		"user_id": "77",
		"time" : 10000, 
		"action": "onPin", 
		"notification_belongs_category": "all",
		"mode": 0,
		"battery": 100,
		"is_charging": True,
		"connectivity": "WIFI",
		"notification_mode":"Vibration",
		"is_screen_on": True,
		"is_power_save": True,
		"is_device_idle": True,
		"call_state": "Idle",
		"day_of_week": 5,
		"time_of_day": 5,
	},
	"behavior_2": {
		"notification_id": 67890,
		"user_id": "88",
		"time" : 15000, 
		"action": "onPin", 
		"notification_belongs_category": "all",
		"mode": 0,
		"battery": 100,
		"is_charging": True,
		"connectivity": "WIFI",
		"notification_mode":"Vibration",
		"is_screen_on": True,
		"is_power_save": True,
		"is_device_idle": True,
		"call_state": "Idle",
		"day_of_week": 5,
		"time_of_day": 5,
	},
	"notification_1": {
		"user_id": "77",
		"notification_id": 12345,
		"app_name": "12345_instagram", 
		"app_title": "XXX", 
		"content": "XXX",
		"post_time": 10000,
		"mode": 0,
		"battery": 100,
		"is_charging": True,
		"connectivity": "WIFI",
		"notification_mode": "Vibration",
		"is_screen_on": True,
		"is_power_save": True,
		"is_device_idle": True,
		"call_state": "Idle",
		"day_of_week": 7,
		"time_of_day": 5,
	},
	"notification_2": {
		"user_id": "88",
		"notification_id": 67890,
		"app_name": "67890_instagram", 
		"app_title": "XXX", 
		"content": "XXX",
		"post_time": 15000,
		"mode": 0,
		"battery": 100,
		"is_charging": True,
		"connectivity": "WIFI",
		"notification_mode": "Vibration",
		"is_screen_on": True,
		"is_power_save": True,
		"is_device_idle": True,
		"call_state": "Idle",
		"day_of_week": 7,
		"time_of_day": 5,
	},
	"activity_recognition_1":{
		"user_id": "77",
		"time": 5000,
		"activity_type": 7,
	},
	"activity_recognition_2":{
		"user_id": "77",
		"time": 9999,
		"activity_type": 7,
	},
	"activity_recognition_3":{
		"user_id": "77",
		"time": 10001,
		"activity_type": 7,
	},
	"activity_recognition_4":{
		"user_id": "88",
		"time": 9000,
		"activity_type": 7,
	},
	"activity_recognition_5":{
		"user_id": "88",
		"time": 14999,
		"activity_type": 7,
	},
	"activity_recognition_6":{
		"user_id": "88",
		"time": 15001,
		"activity_type": 7,
	},
	"recent_use_1": {
		"user_id": "77",
		"time": 6000,
		"action": "open",
	},
	"recent_use_2": {
		"user_id": "88",
		"time": 3000,
		"action": "close",
	},
	"ESM_1": {
		"user_id": "77",
		"survey_finish_time": 10000,
		"mode": 0,
		"esm_context_q1": "x",
		"esm_context_q2": "x",
		"esm_context_q3": "x",
		"esm_context_q4": "x",
		"esm_context_q5": "x",
		"pin_esm_notification_appname": "x",
		"pin_esm_notification_title": "x",
		"pin_esm_notification_content": "x",
		"pin_esm_notification_posttime": "x",
		"esm_category_name": "x",
		"esm_pin_q1": "x",
		"esm_pin_q2": "x",
		"esm_pin_q3": "x",
		"esm_pin_q4": "x",
		"esm_pin_q5": "x",
		"esm_pin_q6": "x",
		"drag_esm_notification_content": "x",
		"drag_esm_notification_appname": "x",
		"drag_esm_notification_posttime": "x",
		"drag_esm_notification_title": "x",
		"esm_drag_q1": "x",
		"esm_drag_q2": "x",
		"esm_drag_q3": "x",
		"esm_drag_q4": "x",
		"esm_drag_q5": "x",
		"esm_drag_q6": "x",
		"esm_category_name": "x",
		"esm_category_q1": "x",
		"esm_auto_compare_original_noti_content": ["x1", "x2"],
		"esm_auto_compare_original_noti_appname": ["x1", "x2"],
		"esm_auto_compare_original_noti_posttime": ["x1", "x2"],
		"esm_auto_compare_original_noti_title": ["x1", "x2"],
		"esm_auto_compare_sort_noti_content": ["x1", "x2"],
		"esm_auto_compare_sort_noti_appname": ["x1", "x2"],
		"esm_auto_compare_sort_noti_posttime": ["x1", "x2"],
		"esm_auto_compare_sort_noti_title": ["x1", "x2"],
		"esm_auto_compare_q1": "x",
		"esm_auto_compare_q2": "x",
		"esm_auto_compare_q3": "x",
		"esm_auto_compare_q4": "x",
	},
	"ESM_2": {
		"user_id": "88",
		"survey_finish_time": 20000,
		"mode": 2,
		"esm_context_q1": "x",
		"esm_context_q2": "x",
		"esm_context_q3": "x",
		"esm_context_q4": "x",
		"esm_context_q5": "x",
		"pin_esm_notification_appname": "x",
		"pin_esm_notification_title": "x",
		"pin_esm_notification_content": "x",
		"pin_esm_notification_posttime": "x",
		"esm_category_name": "x",
		"esm_pin_q1": "x",
		"esm_pin_q2": "x",
		"esm_pin_q3": "x",
		"esm_pin_q4": "x",
		"esm_pin_q5": "x",
		"esm_pin_q6": "x",
		"drag_esm_notification_content": "x",
		"drag_esm_notification_appname": "x",
		"drag_esm_notification_posttime": "x",
		"drag_esm_notification_title": "x",
		"esm_drag_q1": "x",
		"esm_drag_q2": "x",
		"esm_drag_q3": "x",
		"esm_drag_q4": "x",
		"esm_drag_q5": "x",
		"esm_drag_q6": "x",
		"esm_category_name": "x",
		"esm_category_q1": "x",
		"esm_auto_compare_original_noti_content": ["x1", "x2"],
		"esm_auto_compare_original_noti_appname": ["x1", "x2"],
		"esm_auto_compare_original_noti_posttime": ["x1", "x2"],
		"esm_auto_compare_original_noti_title": ["x1", "x2"],
		"esm_auto_compare_sort_noti_content": ["x1", "x2"],
		"esm_auto_compare_sort_noti_appname": ["x1", "x2"],
		"esm_auto_compare_sort_noti_posttime": ["x1", "x2"],
		"esm_auto_compare_sort_noti_title": ["x1", "x2"],
		"esm_auto_compare_q1": "x",
		"esm_auto_compare_q2": "x",
		"esm_auto_compare_q3": "x",
		"esm_auto_compare_q4": "x",
	},
	"diary_1": {
		"user_id": "77",
		"EsmQ1": "11",
		"EsmQ2": "22",
		"EsmQ3": "33",
		"EsmQ4": "44",
		"EsmQ5": "55",
		"EsmQ6": "66",
	},
	"diary_2": {
		"user_id": "88",
		"EsmQ1": "111",
		"EsmQ2": "222",
		"EsmQ3": "333",
		"EsmQ4": "444",
		"EsmQ5": "555",
		"EsmQ6": "666",
	},
	"category_1": {
		"user_id": "77",
		"time" : 10000, 
		"action": "clickCategory", 
		"category_name": "Weather",
		"mode": 0,
		"battery": 100,
		"is_charging": True,
		"connectivity": "WIFI",
		"notification_mode": "Vibration",
		"is_screen_on": True,
		"is_power_save": True,
		"is_device_idle": True,
		"call_state": "Idle",
		"day_of_week": 5,
		"time_of_day": 5,
	},
	"category_2": {
		"user_id": "88",
		"time" : 15000, 
		"action": "clickCategory", 
		"category_name": "Weather",
		"mode": 0,
		"battery": 100,
		"is_charging": True,
		"connectivity": "WIFI",
		"notification_mode": "Vibration",
		"is_screen_on": True,
		"is_power_save": True,
		"is_device_idle": True,
		"call_state": "Idle",
		"day_of_week": 5,
		"time_of_day": 5,
	},
}