behavior_list = [
    {
        "notification_id": 12345,
		"user_id": "77",
		"time" : 111111111111, 
		"action": "startSort", 
		"notification_belongs_category": "all",
		"mode": "manual",
		"battery": 100,
		"is_charging": True,
		"connectivity": "WIFI",
		"notification_mode":"Vibration",
		"is_screen_on": True,
		"is_power_save": True,
		"is_device_idle": True,
		"call_state": "Idle",
		"day_of_week": 5,
		"time_of_day": 5,
    },
    {
        "notification_id": 67890,
		"user_id": "88",
		"time" : 111111111112, 
		"action": "startSort", 
		"notification_belongs_category": "all",
		"mode": "manual",
		"battery": 100,
		"is_charging": True,
		"connectivity": "WIFI",
		"notification_mode":"Vibration",
		"is_screen_on": True,
		"is_power_save": True,
		"is_device_idle": True,
		"call_state": "Idle",
		"day_of_week": 5,
		"time_of_day": 5,
    },
]

notification_list = [
    {
        "user_id": "77",
		"notification_id": 12345,
		"app_name": "12345_instagram", 
		"app_title": "XXX", 
		"content": "XXX",
		"post_time": 5000,
		"mode": "manual",
		"battery": 100,
		"is_charging": True,
		"connectivity": "WIFI",
		"notification_mode":"Vibration",
		"is_screen_on": True,
		"is_power_save": True,
		"is_device_idle": True,
		"call_state": "Idle",
		"day_of_week": 7,
		"time_of_day": 5,
    },
    {
        "user_id": "88",
		"notification_id": 67890,
		"app_name": "67890_instagram", 
		"app_title": "XXX", 
		"content": "XXX",
		"post_time": 5000,
		"mode": "manual",
		"battery": 100,
		"is_charging": True,
		"connectivity": "WIFI",
		"notification_mode":"Vibration",
		"is_screen_on": True,
		"is_power_save": True,
		"is_device_idle": True,
		"call_state": "Idle",
		"day_of_week": 7,
		"time_of_day": 5,
    },
]