name: Testing with GraphQL

on:
  push:
    paths:
    - 'graphql/**'
    - '.github/workflows/graphql.yml'
    
  pull_request:
    paths:
      - 'graphql/**'
      - '.github/workflows/graphql.yml'

jobs:
  testing:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Pytest
      run: |
        cd graphql/
        pip install -r requirements.txt
        pip install pytest
        pytest