name: Testing with GraphQL

on:
  push:
    paths:
    - 'graphql/**'
    - '.github/workflows/graphql.yml'
    
  pull_request:
    paths:
      - 'graphql/**'
      - '.github/workflows/graphql.yml'

jobs:
  testing:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Pytest
      run: |
        cd graphql/
        pip install -r requirements.txt
        pip install pytest
        pytest -v
      env:
        type: ${{ secrets.TYPE }}
        project_id: ${{ secrets.PROJECT_ID }}
        private_key_id: ${{ secrets.PRIVATE_KEY_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        client_email: ${{ secrets.CLIENT_EMAIL }}
        client_id: ${{ secrets.CLIENT_ID }}
        auth_uri: ${{ secrets.AUTH_URI }}
        token_uri: ${{ secrets.TOKEN_URI }}
        auth_provider_x509_cert_url: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
        client_x509_cert_url: ${{ secrets.CLIENT_X509_CERT_URL }}